language: php
php:
  - 5.6

sudo: false

notifications:
  email:
    secure: TNv7WYCJ1ei3wgoXtNM+/Je4ZU7fgcUSsAUQnjC8h2MIE0ImwxPC2xt5t6BR8Mi6XrPCBQ1aRjAvhSFGdYcfhWDJwU0Nq6BfynVwE4OR5/KNhZ9TvMlCQ+eRQD8qJLNqe2MWxMZcdlbrk0rNEhTDcPn3b6dz9Zuji4woe5wksxA=

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=4.3
    - php: 7.1
      env: DB=PGSQL CORE_RELEASE=4.3
    - php: 7.1
      env: DB=SQLITE3 CORE_RELEASE=4.3
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=4.2

before_script:
  - composer self-update || true
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:"^$CORE_RELEASE" --prefer-dist
  - composer require --no-update phpunit/phpunit:^5.7 --prefer-dist
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:~2.0 --prefer-dist --no-update; fi
  - if [[ $DB == SQLITE ]]; then composer require silverstripe/sqlite3:~2.0 --prefer-dist --no-update; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose

script:
  - vendor/bin/phpunit
