---
Name: versioned_helpers
After:
  - "silverstripe/framework/*"
---
SilverStripe\Versioned\ChangeSetItem:
  extensions:
    - 'WebbuildersGroup\VersionedHelpers\Extensions\StagedManyManyChangeSetItem'
