---
Name: versioned_helpers
After:
  - "silverstripe/framework#*"
  - "silverstripe/versioned#*"
---
SilverStripe\Versioned\ChangeSetItem:
  extensions:
    - 'WebbuildersGroup\VersionedHelpers\Extensions\StagedManyManyChangeSetItem'
